# True by default, this is the prefix to the left of the name in chat.
enable_prefix: true

#  True by default, this is the level that appears above the player's head
enable_tag_level: true

# "&aCombat" by default, this is the text that appears after the level above the player's head
tag_name: '&aCombat'

# GOLD by default, change the color of the brackets in the level prefix
prefix_bracket_color: GOLD

# DARK_GREEN by default, change the color of the level in the prefix
prefix_level_color: DARK_GREEN

# Math.round((unarmed + swords + axes + archery + .25 * acrobatics + .25 * taming) / 45) by default
# How the combat is calculated
formula: 'Math.round((unarmed + swords + axes + archery + .25 * acrobatics + .25 * taming) / 45)'

# level up effects
effect:
    lightning: false
    sound:
        # set this empty in order to disable it
        type: ''
        pitch: 0.1
        volume: 1
