name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}

# meta informations for plugin managers and auto updaters
authors:
    - mrphpfan
    - games647
    - 'https://github.com/games647/McCombatLevel/graphs/contributors'
description: |
    ${project.description}
website: ${project.url}
dev-url: ${project.url}

depend: [mcMMO]
softdepend: [Citizens, Herochat]

commands:
  # choose a possible unique name
  ${project.artifactId}:
    description: 'See the combat level'
    usage: /<command> [player]
    aliases: [level, combatlevel]

permissions:
    ${project.artifactId}.*:
        description: 'Gives all permissions for mccombatlevel'
        default: true
        children:
            mccombatlevel.levelcommand.*: true
            mccombatlevel.showLevelTag: true

    ${project.artifactId}.levelcommand.*:
        description: 'Same as mccombatlevel.levelcommand'
        children:
            ${project.artifactId}.levelcommand.others: true
            ${project.artifactId}.levelcommand.self: true

    ${project.artifactId}.levelcommand.others:
        description: 'Show other combat levels'

    ${project.artifactId}.levelcommand.self:
        description: 'Show the own level'

    ${project.artifactId}.showLevelTag:
        description: 'Show the combat level under the name'

    ${project.artifactId}.effect:
        description: 'Play sound and lightning effect on level up'
