name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}

# meta informations for plugin managers and auto updaters
author:
    - mrphpfan
    - games647
    - 'https://github.com/games647/McCombatLevel/graphs/contributors'
description: |
    ${project.description}
website: ${project.url}
dev-url: ${project.url}

depend: [mcMMO]

commands:
  # choose a possible unique name
  combatlevel:
    description: 'See the combat level'
    usage: /<command> [player]
    aliases: [level]

permissions:
    mccombatlevel.*:
        description: 'Gives all permissions for mccombatlevel'
        default: true
        children:
            mccombatlevel.levelcommand.*: true
            mccombatlevel.showLevelTag: true

    mccombatlevel.levelcommand.*:
        description: 'Same as mccombatlevel.levelcommand'
        children:
            mccombatlevel.levelcommand.others: true
            mccombatlevel.levelcommand.self: true

    mccombatlevel.levelcommand.others:
        description: 'Show other combat levels'

    mccombatlevel.levelcommand.self:
        description: 'Show the own level'

    mccombatlevel.showLevelTag:
        description: 'Show the combat level under the name'
